// imports:
import axios from 'axios';
import cheerio from 'cheerio';
import { getSeasonalImagesUrl } from '../lib/getImagesUrl.js';
import { SeasonalInfoType } from '../DTO/seasonal.dto';
/*
Id: number (autogenerated is not the anime's ID),
link: string,
title: string,
producer: string,
images, string[],
genre: sring,
description: string,
score: string but can parsed into number -> maybe later,
members: string
*/

/** @deprecated this function is deprecated please use the new version of this package, check the readme on github https://github.com/Tsukiapp/MAL-scrapper/readme.md */
export default async function getSeasonalInfo(): Promise<SeasonalInfoType[]> { 
  const result: SeasonalInfoType[] = await axios({
    url: 'https://myanimelist.net/anime/season'
  })
    .then(res => {
      const $ = cheerio.load(res.data);

      const animesPerSeason:SeasonalInfoType[] = [];
      $('div.seasonal-anime-list.js-seasonal-anime-list.js-seasonal-anime-list-key-1.clearfix')
        .find('.seasonal-anime')
        .each((i, el): void => {

        if (i < 50 ) {
          const image = $(el).find('.image > a').html();
           animesPerSeason.push({
            ID: i,
            link:  <string> $(el).find('.title > a').attr('href') ,
            title:  <string> $(el).find('.h2_anime_title').text(),
            producer:  <string> $(el).find('.producer > a').text(),
            images: getSeasonalImagesUrl(image),
            genre: <string> $(el).find('.genre > a').attr('title'),
            description: <string> $(el).find('.preline').text(),
            score: <string> $(el).find('.score').text(),
            members: <string> $(el).find('.member').text()
          });
       }
        });
      return animesPerSeason; 
    });
  return result
}
